mode: deployment
replicaCount: 1
image:
  repository: otel/opentelemetry-collector-contrib
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    filter:
      traces:
        span:
          - attributes["url.path"] == "/health"
          - attributes["url.path"] == "/q/health"
          - IsMatch(name, ".*health.*")

    filter/drop_mcp_transport:
      error_mode: ignore
      traces:
        span:
          - |
            kind == SPAN_KIND_CLIENT and
            name == "POST" and
            attributes["server.address"] == "pizza-mcp"
          - |
            resource.attributes["service.name"] == "pizza-mcp" and
            kind == SPAN_KIND_SERVER and
            attributes["http.route"] == "/mcp/messages/:id"

    batch:
      timeout: 10s
      send_batch_size: 1024

  exporters:
    otlp/jaeger:
      endpoint: jaeger-collector.default.svc.cluster.local:4317
      tls:
        insecure: true

  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [filter, filter/drop_mcp_transport, batch]
        exporters: [otlp/jaeger]
